### ISSUE TITLE
What is the pros and cons of Python language?

### ISSUE THREAD

**Issue by letientai299** [ngocyen3006/learn-python#2]
Dich ra tieng Viet: Python co nhung uu va nhuoc diem gi?

**Comment by ngocyen3006** [comment]
# Ưu điểm:
- Cú pháp đơn giản, dễ học.
- Tốc độ xử lý nhanh hơn PHP.
- Hỗ trợ nhiều hệ thống và nền tảng.
- Lập trình hướng đối tượng.
- Một số lượng lớn resources có sẵn cho Python.
# Nhược điểm:
- Python chậm.
- Không phải là ngôn ngữ tốt cho mobile development.
- Không phải là lựa chọn tốt cho nhiệm vụ chuyên sâu bộ nhớ.
- Gần như không thể xây dựng một game high-graphic 3D bằng Python.
- Hạn chế truy cập CSDL.
- Không tốt cho đa xử lý, đa lõi.

**Comment by letientai299** [comment]
Dich o dau ra a :v. Reference o dau thi them cai link vao cho anh nha.

**Comment by ngocyen3006** [comment]
https://www.supinfo.com/articles/single/3425-the-pros-and-cons-of-python

**Comment by ngocyen3006** [comment]
Close issue nha

**Comment by letientai299** [comment]
Oh.
